config:
  backup: true
  banner: true
  create: true
  dotpath: dotfiles
  keepdot: false
  link_by_default: false
  longkey: false
  showdiff: false
  workdir: ~/.config/dotdrop
dotfiles:
  f_zshrc:
    dst: ~/.zshrc
    src: zshrc
profiles:
  pwet.T-mobile.com:
    dotfiles:
    - f_zshrc
