config:
  backup: true
  banner: false
  create: true
  dotpath: dotfiles
  keepdot: false
  link_by_default: true
  longkey: false
  showdiff: false
  workdir: ~/.config/dotdrop
dotfiles:
  d_user:
    dst: ~/Library/Application Support/Sublime Text 3/Packages/User
    link: true
    src: Library/Application Support/Sublime Text 3/Packages/User
  f_async.zsh:
    dst: ~/.oh-my-zsh/custom/async.zsh
    link: true
    src: oh-my-zsh/custom/async.zsh
  f_bitbar_load_temp_fan.10s.sh:
    dst: ~/Documents/Bitbar/load_temp_fan.10s.sh
    link: true
    src: Documents/Bitbar/load_temp_fan.10s.sh
  f_bitbar_timezonesplus.30s.sh:
    dst: ~/Documents/Bitbar/timezonesplus.30s.sh
    link: true
    src: Documents/Bitbar/timezonesplus.30s.sh
  f_btt_autoload_preset.json:
    dst: ~/.btt_autoload_preset.json
    link: true
    src: btt_autoload_preset.json
  f_com.apple.dt.xcode.plist:
    dst: ~/Library/Preferences/com.apple.dt.Xcode.plist
    link: false
    src: Library/Preferences/com.apple.dt.Xcode.plist
  f_default.idekeybindings:
    dst: ~/Library/Developer/Xcode/UserData/KeyBindings/Default.idekeybindings
    link: true
    src: Library/Developer/Xcode/UserData/KeyBindings/Default.idekeybindings
  f_dracula.xccolortheme:
    dst: ~/Library/Developer/Xcode/UserData/FontAndColorThemes/Dracula.xccolortheme
    link: true
    src: Library/Developer/Xcode/UserData/FontAndColorThemes/Dracula.xccolortheme
  f_iterm2_com.googlecode.iterm2.plist:
    dst: ~/Documents/iTerm2/com.googlecode.iterm2.plist
    link: true
    src: Documents/iTerm2/com.googlecode.iterm2.plist
  f_pure.zsh:
    dst: ~/.oh-my-zsh/custom/pure.zsh
    link: true
    src: oh-my-zsh/custom/pure.zsh
  f_zshrc:
    dst: ~/.zshrc
    link: true
    src: zshrc
profiles:
  pwet.T-mobile.com:
    dotfiles:
    - f_zshrc
    - f_async.zsh
    - f_pure.zsh
    - f_bitbar_load_temp_fan.10s.sh
    - f_bitbar_timezonesplus.30s.sh
    - f_iterm2_com.googlecode.iterm2.plist
    - f_dracula.xccolortheme
    - f_com.apple.dt.xcode.plist
    - f_default.idekeybindings
    - f_btt_autoload_preset.json
    - d_user
