config:
  backup: true
  banner: true
  create: true
  dotpath: dotfiles
  keepdot: false
  link_by_default: true
  longkey: false
  showdiff: false
  workdir: ~/.config/dotdrop
dotfiles:
  f_com.googlecode.iterm2.plist:
    dst: ~/Library/Mobile Documents/com~apple~CloudDocs/Stuff/iTerm2/com.googlecode.iterm2.plist
    link: true
    src: Library/Mobile Documents/com~apple~CloudDocs/Stuff/iTerm2/com.googlecode.iterm2.plist
  f_pure.zsh:
    dst: ~/Library/Mobile Documents/com~apple~CloudDocs/Stuff/ohmyzsh/pure.zsh
    link: true
    src: Library/Mobile Documents/com~apple~CloudDocs/Stuff/ohmyzsh/pure.zsh
  f_zshrc:
    dst: ~/.zshrc
    link: true
    src: zshrc
profiles:
  pwet.T-mobile.com:
    dotfiles:
    - f_zshrc
    - f_pure.zsh
    - f_com.googlecode.iterm2.plist
